- name: Deploy
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ec2-user
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      cd /home/ec2-user/nginx-rotate-app

      docker stop nginx-rotate || true
      docker rm nginx-rotate || true

      docker build -t nginx-rotate-app .

      docker run -d \
        --name nginx-rotate \
        -p 9091:80 \
        nginx-rotate-app
